build:
 image: Docker1.12.2
 commands:
  - docker build -t gbase ./GBase
build:
 image: Docker1.12.2
 commands:
  - docker build -t gerrit ./Gerrit
build:
 image: golang
 commands:
  - go get
  - go build
  - go test
