build:
 context: ./GBase
 dockerfile: Dockerfile
build:
 context: ./Gerrit
 dockerfile: Dockerfile
 ports:
  - 8080:8080
 tty: true
build:
 image: golang
 commands:
  - go get
  - go build
  - go test
